// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy1b7pFo2Yjukc66s36gxx6a15_VVWENg',
    appId: '1:918148810697:web:52df7f09fe81c5dda94a18',
    messagingSenderId: '918148810697',
    projectId: 'events-manager-e6c16',
    authDomain: 'events-manager-e6c16.firebaseapp.com',
    storageBucket: 'events-manager-e6c16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCWg9LjMW4c4ura98p2RjQuh3DAQLxbPU',
    appId: '1:918148810697:android:475a79a32e6817c6a94a18',
    messagingSenderId: '918148810697',
    projectId: 'events-manager-e6c16',
    storageBucket: 'events-manager-e6c16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ4h3Bo7X7fbwWysbzZp_kFct71Catdrk',
    appId: '1:918148810697:ios:2e459a379ed05e0ba94a18',
    messagingSenderId: '918148810697',
    projectId: 'events-manager-e6c16',
    storageBucket: 'events-manager-e6c16.firebasestorage.app',
    iosClientId: '918148810697-5ootlmqim8p0v70bc82jnql28r8tbmra.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );
}
